plugins {
    id "com.android.application"
}

android {
    namespace "com.fifteencode.android"
    compileSdk 35

    signingConfigs {
        debugStable {
            storeFile file("signing/15code-debug.keystore")
            storePassword "15code-debug-store"
            keyAlias "15code-debug"
            keyPassword "15code-debug-store"
        }
    }

    defaultConfig {
        applicationId "com.fifteencode.android"
        minSdk 24
        targetSdk 35
        versionCode 27
        versionName "1.3.14"
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debugStable
        }
    }
}
